version: 2
jobs:
  test_classifier:
    working_directory: ~/project  
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout	      
      - run:      
          name: Runnning tests
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py37

workflows:
  version: 2
  test-all:
    jobs:
      - test_classifier            